apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application-deployment
spec:
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
        - name: my-application
          //image: kubobilir/my-application:latest
          image: kubobilir/my-application:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  selector:
    app: my-application
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort